# Use the official Puppeteer image as the base image
FROM ghcr.io/puppeteer/puppeteer:22.11.2

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=TRUE \
PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Switch to the root user to install system dependencies
USER root

# Create the missing directory with appropriate permissions and install required system dependencies
RUN apt-get update && \
    apt-get install -y libgbm1 libasound2

# Switch back to the non-root user
USER pptruser

# Copy the remaining application files
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]

